### ISSUE TITLE
Reload of page and menu item isn't highlighted according to route

### ISSUE THREAD

**Issue by jakcharlton** [mtscout6/react-router-bootstrap#12]
If I click a link, the navbar item is correctly marked 'active' - but on a page reload/refresh it isn't

Actually - just tested what  was seeing, and it isn't marked active at all - not sure why

**Comment by mtscout6** [comment]
Could you provide a code example that illustrates this?

**Comment by mtscout6** [comment]
Are you seeing the same as #21? Or does bcf1f90 fix your issue which was released in v0.8.1?

**Comment by jakcharlton** [comment]
Afraid I cant help much on this, moved off React on this project and it's been a while since I encountered this problem - thanks for the response but will close
