### ISSUE TITLE
Using NavItemLink in Navbar brand

### ISSUE THREAD

**Issue by rothnic** [mtscout6/react-router-bootstrap#18]
I have this working with react-bootstrap, but am having trouble getting it to look right in the Navbar brand property. I saw an example in the react-bootstrap issues [here](https://github.com/react-bootstrap/react-bootstrap/issues/289#issue-49877989), for how they would set the brand. I tried using that example, but change Link to NavItemLink, but I end up with a bullet beside the brand name when using it.

Has anyone been able to use the NavItemLink for the brand?

**Comment by reiniergs** [comment]
try this.

```javascript
  var Brand = (
    <a className="navbar-brand" href="#">Brand</a>
  );
var navbarInstance = (
    <Navbar brand={Brand}>
      <Nav>
        <NavItem eventKey={1} href="#">Link</NavItem>
        <NavItem eventKey={2} href="#">Link</NavItem>
        <DropdownButton eventKey={3} title="Dropdown">
          <MenuItem eventKey="1">Action</MenuItem>
          <MenuItem eventKey="2">Another action</MenuItem>
          <MenuItem eventKey="3">Something else here</MenuItem>
          <MenuItem divider />
          <MenuItem eventKey="4">Separated link</MenuItem>
        </DropdownButton>
      </Nav>
    </Navbar>
  );

React.render(navbarInstance, mountNode);
````

**Comment by mtscout6** [comment]
@reiniergs is right that the brand prop on Navbar is what you want. But I'd suggest that `Brand` uses the `Link` component directly from react-router.

```
var Brand = <Link to='somewhere' className='navbar-brand'>Brand</Link>
```

**Comment by reiniergs** [comment]
you are right, it is more conveniently for navigate users around the
application using Link component when we are integrating with react-router,
I just tried to say that Brand is a component we pass like prop ... very
basic example ...

Rey

**Comment by roblapp** [comment]
I am having the same problem and the proposed solutions here had the same effect. How did you solve this problem?
