### ISSUE TITLE
MenuItemLink doesn't receive active class

### ISSUE THREAD

**Issue by vid** [mtscout6/react-router-bootstrap#20]
in the same code, if I use MenuLink 'active' is added for the current route link, but with MenuItemLink it does not. Thanks!

**Comment by mtscout6** [comment]
Can you provide a code example?

**Comment by vid** [comment]
yes, though In this case it's tested with ButtonLink. Apologies if I got something wrong.

The below adds the active class to the route when using ButtonLink, but when it's changed to this:

`var MyLink = ReactRouterBootstrap.MenuItemLink;`

it does not.

        var React = require('react'), Router = require('react-router');
        var ReactRouterBootstrap = require('react-router-bootstrap')
        var RouteHandler = Router.RouteHandler, Route = Router.Route;

        var ReactBootstrap = require('react-bootstrap');
        var MyLink = ReactRouterBootstrap.ButtonLink;
        

        var NavBar = React.createClass({
          render: function(){
            return (
              <div>
              <nav id="navbar">
              <ul id="nav-pages">
              <MyLink to="/">Home</MyLink>
              <MyLink to="/about">About</MyLink>
              <MyLink to="/contact">Contact</MyLink>
              </ul>
              </nav>
              <RouteHandler />
              </div>
            );
          }
        });

        var home = React.createClass({ render: function() { return (<div>Hi</div>); } });

        var App = NavBar;

        var routes = (
          <Route handler={App} path="/">
            <Route name="/" path="/" handler={home} />
          </Route>
        );

        Router.run(routes, function (Handler) {
          React.render(<Handler/>, document.body);
        });

**Comment by mtscout6** [comment]
And which version of react-router-bootstrap are you using?

**Comment by vid** [comment]
I'm using     "react-router-bootstrap": "^0.8.0"

**Comment by mtscout6** [comment]
Looks like I had a bad unit test: https://github.com/mtscout6/react-router-bootstrap/blob/3f6ec7806454ed8e1a7a22a2236681103222c917/tests/MenuItemLink.spec.js#L62-L67

**Comment by mtscout6** [comment]
Version 0.8.1 is out with the fix.

**Comment by vid** [comment]
Thank you! that fixes it.

**Comment by mtscout6** [comment]
No problem, thanks for reporting it.
