### ISSUE TITLE
Nested routing

### ISSUE THREAD

**Issue by vid** [mtscout6/react-router-bootstrap#21]
Should nested routing work between pages? I've got code like this:

var React = require('react'), Router = require('react-router');
    var ReactRouterBootstrap = require('react-router-bootstrap')
    var RouteHandler = Router.RouteHandler, Route = Router.Route;

    var ReactBootstrap = require('react-bootstrap');
    var MyLink = ReactRouterBootstrap.ButtonLink;

    var NavBar = React.createClass({
      render: function(){
        return (
          <div>
          <nav id="navbar">
          <ul id="nav-pages">
          <MyLink to="/">Home</MyLink>
          <MyLink to="/charts">About</MyLink>
          </ul>
          </nav>
          <RouteHandler />
          </div>
        );
      }
    });

    var home = React.createClass({ render: function() { return (<div>Hi</div>); } });
    var charts = require('./charts.jsx');
    var App = NavBar;

    var routes = (
      <Route handler={App} path="/">
        <Route name="/" path="/" handler={home} />
        <Route name="charts" path="/charts" handler={charts}>
                <Route path=":chart" handler={charts}>
         </Route>
      </Route>
    );

    Router.run(routes, function (Handler) {
      React.render(<Handler/>, document.body);
    });

then charts.jsx:

    var React= require('react'), ReactRouterBootstrap = require('react-router-bootstrap'), MenuItemLink = ReactRouterBootstrap.MenuItemLink;

        var ChooseChart = React.createClass({
          render: function() {
            return (
                <div>
                  <MenuItemLink to="charts" chart="chart1">Chart1</MenuItemLink>
                  <MenuItemLink to="charts" chart="chart2">Chart2</MenuItemLink>
                </div>
            );
          }
        });

But the MenuItemLink items are all active, and their link doesn't function.

Thanks again!

**Comment by mtscout6** [comment]
The `Link` component from react-router behaves the same way. This is because you are linking to charts, which is an active handler in your chain. You need to send your route parameters as well, and then you should be good.

Try:

```
var React= require('react');
var ReactRouterBootstrap = require('react-router-bootstrap');
var MenuItemLink = ReactRouterBootstrap.MenuItemLink;

    var ChooseChart = React.createClass({
      render: function() {
        return (
            <div>
              <MenuItemLink to="charts" params={{chart: "chart1"}}>Chart1</MenuItemLink>
              <MenuItemLink to="charts"  params={{chart: "chart2"}}>Chart2</MenuItemLink>
            </div>
        );
      }
    });
```

Sending a chart prop to the `MenuItemLink` would not help since it would do nothing with it. Whereas chart on a params object will be used with routing. This is similar to how react-router works with `Link`, check out their current [docs](https://github.com/rackt/react-router/blob/cdfb58e028c2fbb974ce6cdf2871d0cc6a15dff5/docs/api/components/Link.md).

**Comment by vid** [comment]
I tried params={{chart: "chart2"}}, now clicking works, but it sends me to the route with no params in the URI.

(I thought the above was what `some="params"` is indicating on the project's README.)

**Comment by mtscout6** [comment]
Looks like the README is out of date, which I'll update later this week. Thanks for pointing out that inconsistency. It should be working similar to react-router's `Link` component.
