### ISSUE TITLE
MenuItemLink requires 'react/addons'

### ISSUE THREAD

**Issue by bryanlarsen** [mtscout6/react-router-bootstrap#22]
this is generally considered bad practice for libraries, and can result in React being loaded multiple times in some scenarios.

LinkMixin, OTOH, does it "right" by requiring 'react/lib/cx' et cetera.

**Comment by mtscout6** [comment]
Could you point me at any docs about this?

**Comment by bryanlarsen** [comment]
I assumed you knew what was going on because you do it the recommended way in LinkMixin.  :)  I'll see if I can find some references.

**Comment by mtscout6** [comment]
I guess it just makes sense so you don't un-intentionally bring the test utils into your production codebase. Thanks for pointing that out.

**Comment by bryanlarsen** [comment]
It appears that the bug that I was referring to was fixed in React 0.10 and browserify 4, so it's probably not relevant.

However, what is relevant is the commented line 26 here:   https://github.com/mtscout6/react-router-bootstrap/pull/23/files#diff-11e9f7f953edc64ba14b0cc350ae7b9dR26

as is, with the line commented out we make ReactRouterBootstrap.js slightly bigger.   Otherwise we require users to make sure that their React global includes addons, which is difficult to do with bower.   But that also means that somebody needs to fix this bug.

**Comment by bryanlarsen** [comment]
woot!  your fix makes pr #23 good to go.
