### ISSUE TITLE
Update with react-bootstrap 0.15

### ISSUE THREAD

**Issue by dozoisch** [mtscout6/react-router-bootstrap#28]
With the update of react-bootrstrap 0.15 (https://github.com/react-bootstrap/react-bootstrap/commit/019304691d282e4ece36c9dc0f73adf397268b85)

We need to changes the includes from `react-bootrstrap/Comp` to `react-bootstrap/lib/Comp`

I can do a PR but I guess, this is the kind of thing that could be done with a simultaneous release!

**Comment by mtscout6** [comment]
Ah, yes I'd love a pull request to get this up to date!

**Comment by dozoisch** [comment]
Fixed with v0.9.1
